// <auto-generated />
namespace BattleChess.Utilities
{
    /// <summary>
    /// Enum types for IChessPiece objects
    /// </summary>
    public enum ChessPieceType
    {
        /// <summary>
        /// King IChessPiece
        /// </summary>
        King,

        /// <summary>
        /// Queen IChessPiece
        /// </summary>
        Queen,

        /// <summary>
        /// Rook IChessPiece
        /// </summary>
        Rook,

        /// <summary>
        /// Bishop IChessPiece
        /// </summary>
        Bishop,

        /// <summary>
        /// Knight IChessPiece
        /// </summary>
        Knight,

        /// <summary>
        /// Pawn IChessPiece
        /// </summary>
        Pawn
    }
}
