// <auto-generated />
namespace BattleChess.Utilities
{
    /// <summary>
    /// Enum for IField and IChessPiece objects
    /// </summary>
    public enum ColorType
    {
        /// <summary>
        /// White Color
        /// </summary>
        White,

        /// <summary>
        /// Black color
        /// </summary>
        Black
    }
}
