// <auto-generated />
namespace BattleChess.Utilities
{
    /// <summary>
    /// Static class containing string constatnts, used as error messages.
    /// </summary>
    public static class ErrorMessages
    {
        /// <summary>
        /// Used by IPosition.Column
        /// </summary>
        public const string InvalidColumn = "The column must be between A and H!";

        /// <summary>
        /// Used by IPosition.Row
        /// </summary>
        public const string InvalidRow = "The row must be between 1 and 8!";

        public const string InvalidColor = "The specified color was not recognised!";
    }
}
