// <auto-generated />
namespace BattleChess.Utilities
{
    /// <summary>
    /// Static class for string constants, contaning image messages
    /// </summary>
    public static class Images
    {
        /// <summary>
        /// Title screen string
        /// </summary>
        public const string TitleScreen = "titleScreen";
    }
}
