// <auto-generated />
namespace BattleChess.Interfaces
{
    /// <summary>
    /// Interface, declaring the implementing objects as one that can do Attack actions
    /// </summary>
    public interface IAttackGenerator
    {
        /// <summary>
        /// Generates an IAttack object
        /// </summary>
        /// <returns>
        /// Returns the generated IAttack object
        /// </returns>
        IAttack GenerateAttack();
    }
}
