// <auto-generated />
namespace BattleChess.Interfaces
{
    /// <summary>
    /// Interface defining basic chess piece actions
    /// </summary>
    public interface IChessPiece : IFactory<IChessPiece>
    {        
    }
}
