// <auto-generated />
namespace BattleChess.Interfaces
{
    /// <summary>
    /// Interface for ChessBoardPiece objects
    /// </summary>
    public interface IChessBoardPiece : IFactory<IChessBoardPiece>
    {
    }
}
