// <auto-generated />

using System.Collections;
using System.Collections.Generic;

namespace BattleChess.Interfaces
{
    using Microsoft.Xna.Framework;

    /// <summary>
    /// Interface for Chess Board objects
    /// </summary>
    public interface IChessBoard : IGameObject, IDrawableAttribute
    {
        /// <summary>
        /// Get's the IField object with the specified position on the chess board
        /// </summary>
        /// <param name="position">The position of the IField object</param>
        /// <returns>The IField object on the specified position</returns>
        IField GetFieldAt(IPosition position);

        ICollection<IField> GetAllFields();
    }
}
