// <auto-generated />

using Microsoft.Xna.Framework;

namespace BattleChess.Interfaces
{
    /// <summary>
    /// Interface defining basic chess piece actions
    /// </summary>
    public interface IChessPiece : IUpdateable, IDrawable, IFactory<IChessPiece>
    {        
    }
}
