// <auto-generated />

namespace BattleChess.Interfaces
{
    using System.Collections.Generic;
    using Microsoft.Xna.Framework;

    /// <summary>
    /// Interface for Chess Board objects
    /// </summary>
    public interface IChessBoard : IGameComponent, IDrawable, IUpdateable
    {
        /// <summary>
        /// Get's the IField object with the specified position on the chess board
        /// </summary>
        /// <param name="position">The position of the IField object</param>
        /// <returns>The IField object on the specified position</returns>
        IField GetFieldAt(IPosition position);
    }
}
