// <auto-generated />
namespace BattleChess.Interfaces
{
    /// <summary>
    /// Interface, declaring the implementing objects as one that can do Defense actions
    /// </summary>
    public interface IDefenseGenerator
    {
        /// <summary>
        /// Generates an IDefense object
        /// </summary>
        /// <returns>
        /// Returns the generated IDefense object
        /// </returns>
        IDefense GenerateDefense();
    }
}
