// <auto-generated />
namespace BattleChess.Interfaces
{
    /// <summary>
    /// Interface declaring an Execute method. Ref. - Command Pattern [GOF]
    /// </summary>
    public interface IExecutable
    {
        /// <summary>
        /// Executes a set of actions, defined by the implementing object
        /// </summary>
        void Execute();
    }
}
