// <auto-generated />
namespace BattleChess.Interfaces
{
    /// <summary>
    /// Interface which declares a Create factory method. Ref. - Factory Method [GOF]
    /// </summary>
    /// <typeparam name="T">The type of the class which implements the interface</typeparam>
    public interface IFactory<out T>
    {
        /// <summary>
        /// Factory method
        /// </summary>
        /// <returns>
        /// Returns a new object of type T
        /// </returns>
        T Create();
    }
}
