// <auto-generated />

namespace BattleChess.Interfaces
{
    /// <summary>
    /// Interface for ChessBoardPiece objects
    /// </summary>
    public interface IField : IFactory<IField>
    {
        /// <summary>
        /// Gets Chess Piece placed in this field. Can be null.
        /// </summary>
        /// <returns>The Chess Piece or null.</returns>
        IChessPiece GetChessPiece();

        /// <summary>
        /// Sets the Chess Piece in this field.
        /// </summary>
        /// <param name="chessPiece">The object to be set.</param>
        void SetChessPiece(IChessPiece chessPiece);
    }
}
