// <auto-generated />

namespace BattleChess.Interfaces
{
    using BattleChess.Infrastructure;
    using Microsoft.Xna.Framework;

    /// <summary>
    /// Interface for ChessBoardPiece objects
    /// </summary>
    public interface IField : IUpdateable, IDrawable, IFactory<IField>
    {
        Position Position { get; }

        /// <summary>
        /// The Chess Piece in this Field. Can be null.
        /// </summary>
        IChessPiece ChessPiece {get; set; }
    }
}
