// <auto-generated />
namespace BattleChess.Interfaces
{
    /// <summary>
    /// Interface, declaring the implementing objects as one that can do Move actions
    /// </summary>
    public interface IMoveGenerator
    {
        /// <summary>
        /// Generates an IMove object
        /// </summary>
        /// <returns>
        /// Returns the generated IMove object
        /// </returns>
        IMove GenerateMove();
    }
}
