// <auto-generated />
namespace BattleChess.Interfaces
{
    using System;

    /// <summary>
    /// Interface for Position objects
    /// </summary>
    public interface IPosition : IEquatable<IPosition>
    {
        /// <summary>
        /// Returns the Column("x") param of the IPosition object 
        /// </summary>
        char Column { get; }

        /// <summary>
        /// Returns the Row("y") param of the IPosition object
        /// </summary>
        int Row { get; }
    }
}
