// <auto-generated />
namespace BattleChess.Infrastructure
{
    using System;
    using System.Collections.Generic;
    using Interfaces;
    using Microsoft.Xna.Framework;

    /// <summary>
    /// Concrete implementation of IChessBoard. Extends DrawableGameComponent
    /// </summary>
    public class ChessBoard : DrawableGameComponent, IChessBoard
    {
        private readonly Dictionary<IPosition, IField> chessBoard = new Dictionary<IPosition, IField>(); 

        /// <summary>
        /// ChessBoard constructor
        /// </summary>
        /// <param name="game"></param>
        public ChessBoard(Game game) 
            : base(game)
        {
        }

        public IField GetFieldAt(IPosition position)
        {
            throw new NotImplementedException();
        }
    }
}
