// <auto-generated />
namespace BattleChess.Infrastructure
{
    using Interfaces;

    /// <summary>
    /// Concrete implementation of IMove
    /// </summary>
    public class Move : IMove
    {
        /// <summary>
        /// Constructor with no arguments. Used by the Create method
        /// </summary>
        public Move()
        {
        }

        /// <summary>
        /// Constructor for the Move Object
        /// </summary>
        /// <param name="from">The Move From IField object</param>
        /// <param name="to">The Move To IField object</param>
        public Move(IField from, IField to)
        {
            this.From = from;
            this.To = to;
        }

        public IField From { get; set; }

        public IField To { get; set; }

        public void Execute()
        {
            throw new System.NotImplementedException();
        }

        public IMove Create()
        {
            throw new System.NotImplementedException();
        }
    }
}
