// <auto-generated />
namespace BattleChess.Infrastructure
{
    using System.Collections.Generic;
    using Interfaces;

    /// <summary>
    /// Concrete implementation of IMovePattern
    /// </summary>
    public class PawnMovePattern : IMovePattern
    {
        /// <summary>
        /// A singleton IMovePattern object for the PawnMovePattern implemenation. Ref. Singleton [GOF]
        /// </summary>
        public static readonly IMovePattern Instance = new PawnMovePattern();

        private PawnMovePattern()
        {
            //Singleton. Ref. - Singleton [GOF]
        }

        public ICollection<IMove> GeneratePossibleMoves(IField currentField)
        {
            throw new System.NotImplementedException();
        }
    }
}
